# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package TF2.15

on:
  push:
    branches: [ master ]
  pull_request:

env:
  TF_KERAS_VIS_MAX_STEPS: 3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        tensorflow: ['2.6.0', '2.7.0', '2.8.0', '2.9.0', '2.10.0', '2.11.0', '2.12.0', '2.13.0', '2.14.0', '2.15.0']
      include:
        - python-version: '3.11'
          tensorflow: '2.12.0'
        - python-version: '3.11'
          tensorflow: '2.13.0'
        - python-version: '3.11'
          tensorflow: '2.14.0'
        - python-version: '3.11'
          tensorflow: '2.15.0'
      exclude:
        - python-version: '3.8'
          tensorflow: '2.14.0'
        - python-version: '3.8'
          tensorflow: '2.15.0'
        - python-version: '3.10'
          tensorflow: '2.6.0'
        - python-version: '3.10'
          tensorflow: '2.7.0'
          
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade -e .[develop,examples] tensorflow~=${{ matrix.tensorflow }}
    - name: Test with pytest
      run: |
        pytest -n auto --dist loadscope
      timeout-minutes: 60
    - name: Test attentions.ipynb
      run: |
        jupyter-nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute examples/attentions.ipynb
    - name: Test visualize_dense_layer.ipynb
      run: |
        jupyter-nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute examples/visualize_dense_layer.ipynb
    - name: Test visualize_conv_filters.ipynb
      run: |
        jupyter-nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute examples/visualize_conv_filters.ipynb
